alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: APP_NAME
  scope: RUN_AND_BUILD_TIME
  value: Punto de venta
- key: VITE_APP_NAME
  scope: RUN_AND_BUILD_TIME
  value: Punto de venta
- key: APP_ENV
  scope: RUN_AND_BUILD_TIME
  value: production
- key: APP_KEY
  scope: RUN_AND_BUILD_TIME
  value: base64:5kp9GwSSgEjWfD4hfCKhvqDrQxxaPrS7xcD2Ao3iu2g=
- key: APP_DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: APP_TIMEZONE
  scope: RUN_AND_BUILD_TIME
  value: America/Mexico_City
- key: APP_URL
  scope: RUN_AND_BUILD_TIME
  value: https://pos-app-rpts9.ondigitalocean.app
- key: VITE_APP_URL
  scope: RUN_AND_BUILD_TIME
  value: https://pos-app-rpts9.ondigitalocean.app
- key: APP_LOCALE
  scope: RUN_AND_BUILD_TIME
  value: en
- key: APP_FALLBACK_LOCALE
  scope: RUN_AND_BUILD_TIME
  value: en
- key: APP_FAKER_LOCALE
  scope: RUN_AND_BUILD_TIME
  value: en_US
- key: APP_MAINTENANCE_DRIVER
  scope: RUN_AND_BUILD_TIME
  value: file
- key: BCRYPT_ROUNDS
  scope: RUN_AND_BUILD_TIME
  value: "12"
- key: LOG_CHANNEL
  scope: RUN_AND_BUILD_TIME
  value: stack
- key: LOG_STACK
  scope: RUN_AND_BUILD_TIME
  value: single
- key: LOG_DEPRECATIONS_CHANNEL
  scope: RUN_AND_BUILD_TIME
  value: "null"
- key: LOG_LEVEL
  scope: RUN_AND_BUILD_TIME
  value: debug
- key: DB_CONNECTION
  scope: RUN_AND_BUILD_TIME
  value: mysql
- key: DB_HOST
  scope: RUN_AND_BUILD_TIME
  value: db-pos-app-do-user-39295698-0.m.db.ondigitalocean.com
- key: DB_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25060"
- key: DB_DATABASE
  scope: RUN_AND_BUILD_TIME
  value: pos-app-db
- key: DB_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: pos-user
- key: DB_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${DB_PASSWORD}
- key: SESSION_DRIVER
  scope: RUN_AND_BUILD_TIME
  value: database
- key: SESSION_LIFETIME
  scope: RUN_AND_BUILD_TIME
  value: "120"
- key: SESSION_ENCRYPT
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: SESSION_PATH
  scope: RUN_AND_BUILD_TIME
  value: /
- key: SESSION_DOMAIN
  scope: RUN_AND_BUILD_TIME
  value: "null"
- key: BROADCAST_CONNECTION
  scope: RUN_AND_BUILD_TIME
  value: log
- key: FILESYSTEM_DISK
  scope: RUN_AND_BUILD_TIME
  value: local
- key: QUEUE_CONNECTION
  scope: RUN_AND_BUILD_TIME
  value: database
- key: CACHE_STORE
  scope: RUN_AND_BUILD_TIME
  value: database
- key: CACHE_PREFIX
  scope: RUN_AND_BUILD_TIME
- key: MEMCACHED_HOST
  scope: RUN_AND_BUILD_TIME
  value: 127.0.0.1
- key: REDIS_CLIENT
  scope: RUN_AND_BUILD_TIME
  value: phpredis
- key: REDIS_HOST
  scope: RUN_AND_BUILD_TIME
  value: 127.0.0.1
- key: REDIS_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: "null"
- key: REDIS_PORT
  scope: RUN_AND_BUILD_TIME
  value: "6379"
- key: MAIL_MAILER
  scope: RUN_AND_BUILD_TIME
  value: log
- key: MAIL_HOST
  scope: RUN_AND_BUILD_TIME
  value: 127.0.0.1
- key: MAIL_PORT
  scope: RUN_AND_BUILD_TIME
  value: "2525"
- key: MAIL_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: "null"
- key: MAIL_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: "null"
- key: MAIL_ENCRYPTION
  scope: RUN_AND_BUILD_TIME
  value: "null"
- key: MAIL_FROM_ADDRESS
  scope: RUN_AND_BUILD_TIME
  value: hello@example.com
- key: MAIL_FROM_NAME
  scope: RUN_AND_BUILD_TIME
  value: ${APP_NAME}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
- key: AWS_DEFAULT_REGION
  scope: RUN_AND_BUILD_TIME
  value: us-east-1
- key: AWS_BUCKET
  scope: RUN_AND_BUILD_TIME
- key: AWS_USE_PATH_STYLE_ENDPOINT
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: PRINTER_NAME
  scope: RUN_AND_BUILD_TIME
  value: IMPRESORA3
- key: APP_RUN_MIGRATIONS
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: APP_SUPER_ADMIN_USER
  scope: RUN_AND_BUILD_TIME
  value: super-admin
- key: APP_SUPER_ADMIN_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: super_admin
- key: APP_SUPER_ADMIN_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: superadmin@superadmin.com
- key: APP_ADMIN_USER
  scope: RUN_AND_BUILD_TIME
  value: admin
- key: APP_ADMIN_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: admin1234
- key: APP_ADMIN_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: admin@pos-app.com
- key: APP_USER_USER
  scope: RUN_AND_BUILD_TIME
  value: employe
- key: APP_USER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: employe1234
- key: APP_USER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: employe@pos-app.com
- key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: VITE_REVERB_APP_KEY
  scope: RUN_AND_BUILD_TIME
  value: 4mymudn0cfhsfyrx2h2d
- key: VITE_REVERB_HOST
  scope: RUN_AND_BUILD_TIME
  value: pos-app-rpts9.ondigitalocean.app
- key: VITE_REVERB_PORT
  scope: RUN_AND_BUILD_TIME
  value: "443"
- key: VITE_REVERB_SCHEME
  scope: RUN_AND_BUILD_TIME
  value: https
- key: REVERB_APP_ID
  scope: RUN_TIME
  value: "210086"
- key: REVERB_APP_KEY
  scope: RUN_TIME
  value: 4mymudn0cfhsfyrx2h2d
- key: REVERB_APP_SECRET
  scope: RUN_TIME
  value: 8dxxpiulrmffeptslzgy
- key: REVERB_HOST
  scope: RUN_TIME
  value: pos-app-rpts9.ondigitalocean.app
- key: REVERB_PORT
  scope: RUN_TIME
  value: "443"
- key: REVERB_SCHEME
  scope: RUN_TIME
  value: https
- key: REVERB_SERVER_PORT
  scope: RUN_TIME
  value: "6001"
- key: BROADCAST_CONNECTION
  scope: RUN_TIME
  value: reverb
features:
- buildpack-stack=ubuntu-22
name: pos-app
region: sfo
services:
- dockerfile_path: /Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: sfadiego/punto-venta
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: punto-venta
  source_dir: /
