export enum ApiRoutes {
    Auth = "/api/auth",
    Logout = "/api/auth/logout",
    Orders = "/api/order",
    OrderSalesByCategory = "/api/order/sales-by-category",
    Category = "/api/category",
    Customer = "/api/customer",
    Product = "/api/product",
    System = "/api/admin/system",
    Statistics = "/api/admin/system/statistics",
    AdminUsers = "/api/admin/users",
    PaymentMethods = "/api/admin/payment-methods",
    BusinessConfig = "/api/admin/config",
    Files = "/api/files",
    PrintBytes     = "/api/order/:id/print/bytes",
    PrintTestBytes = "/api/order/print/test-bytes",
    Tenant = "/api/tenant",
    DemoRequest = "/api/demo-request",
    SuperAdminAuth         = "/api/super-admin/auth",
    SuperAdminTenant       = "/api/super-admin/tenant",
    SuperAdminSubscription = "/api/super-admin/subscription",
    SuperAdminSettings     = "/api/super-admin/settings",
    SuperAdminErrorLogs    = "/api/super-admin/error-logs",
    SuperAdminPrinterAgent = "/api/super-admin/printer-agent/download",
    SuperAdminDemoRequests = "/api/super-admin/demo-requests",
    ClientErrorLog         = "/api/client-error",
}
