export enum ApiRoutes {
    Auth = "/api/auth",
    Orders = "/api/order",
    OrderSalesByCategory = "/api/order/sales-by-category",
    Category = "/api/category",
    Product = "/api/product",
    System = "/api/admin/system",
    Statistics = "/api/admin/system/statistics",
    BusinessConfig = "/api/admin/config",
    Files = "/api/files",
    PrintBytes = "/api/order/:id/print/bytes",
    Tenant = "/api/tenant",
    SuperAdminAuth         = "/api/super-admin/auth",
    SuperAdminTenant       = "/api/super-admin/tenant",
    SuperAdminSubscription = "/api/super-admin/subscription",
    SuperAdminSettings     = "/api/super-admin/settings",
}
