// Debe reflejar los cases de app/Enums/FeatureSpotlightEnum.php
export enum FeatureSpotlightKey {
    RolePermissions = "role_permissions",
    ExpensesButton = "expenses_button",
    CustomerSection = "customer_section",
    UsersSection = "users_section",
    ProductSection = "product_section",
    CategoriesSection = "categories_section",
    ConfigurationSection = "configuration_section",
    DeliverySection = "delivery_section",
    DeliverySectionButton = "delivery_section_button",
    SubscriptionSection = "subscription_section",
    OnlineMenuSection = "online_menu_section",
    OrderListSection = "order_list_section",
    TicketSection = "ticket_section",
    FilterSalesByDateMonth = "filter_sales_by_date_month",
    ReadonlyMenuSection = "readonly_menu_section",
    ProvidersNavItem = "providers_nav_item",
    ProvidersSettingsSection = "providers_settings_section",
}
