export enum AdminRoutes {
    Dashboard    = "/",
    QuickSale    = "/quick-sale",
    CloseSales   = "/close-sales",
    ProductsPage = "/products",
    OrderList    = "/orders",
    TakeOrder    = "/take-order/:id",
    CategoryList = "/categories",
    CustomerList = "/customers",
    CustomerDetail = "/customers/:id",
    ProviderList = "/providers",
    ProviderDetail = "/providers/:id",
    EmployeeList = "/employees",
    EmployeeDetail = "/employees/:id",
    Statistics   = "/statistics",
    SaleList     = "/sales",
    Users        = "/users",
    Admin        = "/admin",
    Subscription = "/subscription",
    TenantAuth   = "/:slug/auth",
    PublicMenu   = "/:slug/menu",
}

export enum SuperAdminRoutes {
    Login         = "/admin/login",
    Tenants       = "/admin/tenants",
    NewTenant     = "/admin/tenants/new",
    EditTenant    = "/admin/tenants/:id",
    TenantUsers   = "/admin/tenants/:id/users",
    Subscriptions = "/admin/subscriptions",
    Settings      = "/admin/settings",
    ErrorLogs     = "/admin/error-logs",
    ClientLeads   = "/admin/client-leads",
}
