// Catálogo curado de íconos OpenMoji (CC BY-SA 4.0, ver /NOTICE.md) vendorizados en
// public/images/product-icons/. `key` es el hexcode Unicode del archivo SVG.
export interface IOpenmojiIcon {
    key: string;
    label: string;
    group: string;
}

export const OPENMOJI_CATALOG: IOpenmojiIcon[] = [
    { key: "1F991", label: "Calamar", group: "Carnes y mariscos" },
    { key: "1F990", label: "Camarón", group: "Carnes y mariscos" },
    { key: "1F437", label: "Cerdo", group: "Carnes y mariscos" },
    { key: "1F416", label: "Cerdo (cuerpo)", group: "Carnes y mariscos" },
    { key: "1F980", label: "Jaiba", group: "Carnes y mariscos" },
    { key: "1F99E", label: "Langosta", group: "Carnes y mariscos" },
    { key: "1F41F", label: "Pescado", group: "Carnes y mariscos" },
    { key: "1F414", label: "Pollo", group: "Carnes y mariscos" },
    { key: "1F419", label: "Pulpo", group: "Carnes y mariscos" },
    { key: "1F9C4", label: "Ajo", group: "Verduras" },
    { key: "1F336", label: "Ají picante", group: "Verduras" },
    { key: "1FADB", label: "Arveja", group: "Verduras" },
    { key: "1F346", label: "Berenjena", group: "Verduras" },
    { key: "1F966", label: "Brócoli", group: "Verduras" },
    { key: "1F330", label: "Castaña", group: "Verduras" },
    { key: "1F9C5", label: "Cebolla", group: "Verduras" },
    { key: "1F344-200D-1F7EB", label: "Champiñón", group: "Verduras" },
    { key: "1F33D", label: "Choclo", group: "Verduras" },
    { key: "1F96C", label: "Hoja verde", group: "Verduras" },
    { key: "1FADA", label: "Jengibre", group: "Verduras" },
    { key: "1FAD8", label: "Legumbres", group: "Verduras" },
    { key: "1F95C", label: "Maní", group: "Verduras" },
    { key: "1F951", label: "Palta", group: "Verduras" },
    { key: "1F954", label: "Papa", group: "Verduras" },
    { key: "1FADD", label: "Pepinillo", group: "Verduras" },
    { key: "1F952", label: "Pepino", group: "Verduras" },
    { key: "1FAD1", label: "Pimentón", group: "Verduras" },
    { key: "1FADC", label: "Tubérculo", group: "Verduras" },
    { key: "1F955", label: "Zanahoria", group: "Verduras" },
    { key: "1FAD2", label: "Aceituna", group: "Frutas" },
    { key: "1FAD0", label: "Arándanos", group: "Frutas" },
    { key: "1F352", label: "Cerezas", group: "Frutas" },
    { key: "1F965", label: "Coco", group: "Frutas" },
    { key: "1F351", label: "Durazno", group: "Frutas" },
    { key: "1F353", label: "Frutilla", group: "Frutas" },
    { key: "1F95D", label: "Kiwi", group: "Frutas" },
    { key: "1F34B-200D-1F7E9", label: "Lima", group: "Frutas" },
    { key: "1F34B", label: "Limón", group: "Frutas" },
    { key: "1F34A", label: "Mandarina", group: "Frutas" },
    { key: "1F96D", label: "Mango", group: "Frutas" },
    { key: "1F34E", label: "Manzana roja", group: "Frutas" },
    { key: "1F34F", label: "Manzana verde", group: "Frutas" },
    { key: "1F348", label: "Melón", group: "Frutas" },
    { key: "1F350", label: "Pera", group: "Frutas" },
    { key: "1F34D", label: "Piña", group: "Frutas" },
    { key: "1F34C", label: "Plátano", group: "Frutas" },
    { key: "1F349", label: "Sandía", group: "Frutas" },
    { key: "1F345", label: "Tomate", group: "Frutas" },
    { key: "1F347", label: "Uvas", group: "Frutas" },
    { key: "1F96F", label: "Bagel", group: "Preparados y panadería" },
    { key: "1F963", label: "Bowl", group: "Preparados y panadería" },
    { key: "1F32F", label: "Burrito", group: "Preparados y panadería" },
    { key: "1F37F", label: "Cabritas", group: "Preparados y panadería" },
    { key: "1F969", label: "Carne / Res", group: "Preparados y panadería" },
    { key: "1F373", label: "Cocinando", group: "Preparados y panadería" },
    { key: "1F96B", label: "Conservas", group: "Preparados y panadería" },
    { key: "1F356", label: "Costillar", group: "Preparados y panadería" },
    { key: "1F950", label: "Croissant", group: "Preparados y panadería" },
    { key: "1F957", label: "Ensalada", group: "Preparados y panadería" },
    { key: "1F9C6", label: "Falafel", group: "Preparados y panadería" },
    { key: "1FAD5", label: "Fondue", group: "Preparados y panadería" },
    { key: "1F354", label: "Hamburguesa", group: "Preparados y panadería" },
    { key: "1F32D", label: "Hot dog", group: "Preparados y panadería" },
    { key: "1F95A", label: "Huevo", group: "Preparados y panadería" },
    { key: "1F9C8", label: "Mantequilla", group: "Preparados y panadería" },
    { key: "1F956", label: "Marraqueta", group: "Preparados y panadería" },
    { key: "1F372", label: "Olla", group: "Preparados y panadería" },
    { key: "1F35E", label: "Pan molde", group: "Preparados y panadería" },
    { key: "1FAD3", label: "Pan pita", group: "Preparados y panadería" },
    { key: "1F959", label: "Pan relleno", group: "Preparados y panadería" },
    { key: "1F95E", label: "Panqueques", group: "Preparados y panadería" },
    { key: "1F35F", label: "Papas fritas", group: "Preparados y panadería" },
    { key: "1F355", label: "Pizza", group: "Preparados y panadería" },
    { key: "1F357", label: "Pollo (trozo)", group: "Preparados y panadería" },
    { key: "1F968", label: "Pretzel", group: "Preparados y panadería" },
    { key: "1F9C0", label: "Queso", group: "Preparados y panadería" },
    { key: "1F9C2", label: "Sal", group: "Preparados y panadería" },
    { key: "1F958", label: "Sartén", group: "Preparados y panadería" },
    { key: "1F96A", label: "Sándwich", group: "Preparados y panadería" },
    { key: "1F32E", label: "Taco", group: "Preparados y panadería" },
    { key: "1FAD4", label: "Tamal", group: "Preparados y panadería" },
    { key: "1F953", label: "Tocino", group: "Preparados y panadería" },
    { key: "1F9C7", label: "Waffle", group: "Preparados y panadería" },
    { key: "1F35A", label: "Arroz cocido", group: "Cocina asiática" },
    { key: "1F35B", label: "Arroz con curry", group: "Cocina asiática" },
    { key: "1F371", label: "Bento", group: "Cocina asiática" },
    { key: "1F359", label: "Bola de arroz", group: "Cocina asiática" },
    { key: "1F364", label: "Camarón frito", group: "Cocina asiática" },
    { key: "1F360", label: "Camote asado", group: "Cocina asiática" },
    { key: "1F961", label: "Comida para llevar", group: "Cocina asiática" },
    { key: "1F361", label: "Dango", group: "Cocina asiática" },
    { key: "1F95F", label: "Dumpling", group: "Cocina asiática" },
    { key: "1F35D", label: "Espagueti", group: "Cocina asiática" },
    { key: "1F358", label: "Galleta de arroz", group: "Cocina asiática" },
    { key: "1F960", label: "Galleta de la fortuna", group: "Cocina asiática" },
    { key: "1F362", label: "Oden", group: "Cocina asiática" },
    { key: "1F96E", label: "Pastel de luna", group: "Cocina asiática" },
    { key: "1F365", label: "Pastel de pescado", group: "Cocina asiática" },
    { key: "1F35C", label: "Sopa", group: "Cocina asiática" },
    { key: "1F363", label: "Sushi", group: "Cocina asiática" },
    { key: "1F36B", label: "Chocolate", group: "Dulces y postres" },
    { key: "1F36D", label: "Chupete", group: "Dulces y postres" },
    { key: "1F9C1", label: "Cupcake", group: "Dulces y postres" },
    { key: "1F369", label: "Dona", group: "Dulces y postres" },
    { key: "1F36C", label: "Dulce", group: "Dulces y postres" },
    { key: "1F36E", label: "Flan", group: "Dulces y postres" },
    { key: "1F36A", label: "Galleta", group: "Dulces y postres" },
    { key: "1F368", label: "Helado", group: "Dulces y postres" },
    { key: "1F366", label: "Helado suave", group: "Dulces y postres" },
    { key: "1F36F", label: "Miel", group: "Dulces y postres" },
    { key: "1F367", label: "Raspado", group: "Dulces y postres" },
    { key: "1F967", label: "Tarta", group: "Dulces y postres" },
    { key: "1F370", label: "Torta", group: "Dulces y postres" },
    { key: "1F382", label: "Torta cumpleaños", group: "Dulces y postres" },
    { key: "1F964", label: "Bebida con bombilla", group: "Bebidas" },
    { key: "1F9C3", label: "Bebida en caja", group: "Bebidas" },
    { key: "1F37E", label: "Botella", group: "Bebidas" },
    { key: "1F942", label: "Brindis", group: "Bebidas" },
    { key: "1F9CB", label: "Bubble tea", group: "Bebidas" },
    { key: "2615", label: "Café", group: "Bebidas" },
    { key: "1F37A", label: "Cerveza", group: "Bebidas" },
    { key: "1F37B", label: "Cervezas", group: "Bebidas" },
    { key: "1F378", label: "Cóctel", group: "Bebidas" },
    { key: "1F9CA", label: "Hielo", group: "Bebidas" },
    { key: "1F95B", label: "Leche", group: "Bebidas" },
    { key: "1FAD7", label: "Líquido", group: "Bebidas" },
    { key: "1F37C", label: "Mamadera", group: "Bebidas" },
    { key: "1F9C9", label: "Mate", group: "Bebidas" },
    { key: "1F376", label: "Sake", group: "Bebidas" },
    { key: "1FAD6", label: "Tetera", group: "Bebidas" },
    { key: "1F379", label: "Trago tropical", group: "Bebidas" },
    { key: "1F375", label: "Té", group: "Bebidas" },
    { key: "1F377", label: "Vino", group: "Bebidas" },
    { key: "1F943", label: "Whisky", group: "Bebidas" },
    { key: "1F374", label: "Cubiertos", group: "Utensilios" },
    { key: "1F944", label: "Cuchara", group: "Utensilios" },
    { key: "1F52A", label: "Cuchillo", group: "Utensilios" },
    { key: "1FAD9", label: "Frasco", group: "Utensilios" },
    { key: "1F962", label: "Palillos", group: "Utensilios" },
    { key: "1F37D", label: "Plato servido", group: "Utensilios" },
    { key: "1F3FA", label: "Ánfora", group: "Utensilios" },
    { key: "E153", label: "Leche (jarra)", group: "Otros" },
    { key: "E0D0", label: "Molino de sal", group: "Otros" },
    { key: "E0CA", label: "Pan hallulla", group: "Otros" },
    { key: "1F3EA", label: "Tienda / abarrotes", group: "Tienda y compras" },
    { key: "1F6D2", label: "Carro de compras", group: "Tienda y compras" },
    { key: "1F9FA", label: "Canasta", group: "Tienda y compras" },
    { key: "1F6CD", label: "Bolsas de compras", group: "Tienda y compras" },
    // Reutiliza íconos ya vendorizados en otros grupos (mismo archivo, etiqueta en español
    // mexicano) más 1F335, agregado específicamente para este grupo.
    { key: "1F32E", label: "Taco", group: "Comida mexicana" },
    { key: "1F32F", label: "Burrito", group: "Comida mexicana" },
    { key: "1FAD4", label: "Tamal", group: "Comida mexicana" },
    { key: "1FAD3", label: "Tortilla", group: "Comida mexicana" },
    { key: "1F336", label: "Chile", group: "Comida mexicana" },
    { key: "1F33D", label: "Elote", group: "Comida mexicana" },
    { key: "1F951", label: "Aguacate", group: "Comida mexicana" },
    { key: "1FAD8", label: "Frijoles", group: "Comida mexicana" },
    { key: "1F9C4", label: "Ajo", group: "Comida mexicana" },
    { key: "1F9C5", label: "Cebolla", group: "Comida mexicana" },
    { key: "1F345", label: "Tomate", group: "Comida mexicana" },
    { key: "1F9C0", label: "Queso", group: "Comida mexicana" },
    { key: "1F943", label: "Tequila", group: "Comida mexicana" },
    { key: "1F335", label: "Nopal / cactus", group: "Comida mexicana" },
    // OpenMoji solo define 4 íconos de carne-como-comida en todo el set (bacon, carne, costillar,
    // hamburguesa) — no hay glifos separados para "cerdo preparado" o cortes específicos, así que
    // se agrupan los mismos archivos de "Preparados y panadería" aquí para que sean fáciles de
    // encontrar juntos al buscar carne/cerdo.
    { key: "1F969", label: "Carne", group: "Carnes" },
    { key: "1F356", label: "Costillar / jamón", group: "Carnes" },
    { key: "1F953", label: "Tocino", group: "Carnes" },
    { key: "1F357", label: "Pollo (trozo)", group: "Carnes" },
    { key: "1F354", label: "Hamburguesa", group: "Carnes" },
    { key: "1F404", label: "Res / vaca", group: "Carnes" },
    { key: "1F9B4", label: "Hueso", group: "Carnes" },
    { key: "E312", label: "Hígado", group: "Carnes" },
    { key: "1F9B6", label: "Pata / cuero", group: "Carnes" },
    { key: "E0CE", label: "Especias", group: "Otros" },
    { key: "1F33F", label: "Hierbas", group: "Otros" },
    // Grupos para negocios tipo Retail (BusinessTypeEnum::Retail) — tiendas de chucherías,
    // cosméticos, juguetes, bazar — que no venden comida.
    { key: "1F484", label: "Labial", group: "Cosméticos" },
    { key: "1F485", label: "Esmalte de uñas", group: "Cosméticos" },
    { key: "1F9F4", label: "Loción / crema", group: "Cosméticos" },
    { key: "1FA9E", label: "Espejo", group: "Cosméticos" },
    { key: "1FA92", label: "Rastrillo", group: "Cosméticos" },
    { key: "1F9FC", label: "Jabón", group: "Cosméticos" },
    { key: "1FAA5", label: "Cepillo de dientes", group: "Cosméticos" },
    { key: "1F48D", label: "Anillo", group: "Cosméticos" },
    { key: "1F9F8", label: "Peluche", group: "Juguetes" },
    { key: "1F388", label: "Globo", group: "Juguetes" },
    { key: "1FA80", label: "Yoyo", group: "Juguetes" },
    { key: "1F3B2", label: "Dados", group: "Juguetes" },
    { key: "1F9E9", label: "Rompecabezas", group: "Juguetes" },
    { key: "1FA81", label: "Cometa", group: "Juguetes" },
    { key: "1F3AE", label: "Control de videojuego", group: "Juguetes" },
    { key: "26BD", label: "Pelota", group: "Juguetes" },
    { key: "1FAE3", label: "Balde", group: "Artículos para el hogar" },
    { key: "1F9F9", label: "Escoba", group: "Artículos para el hogar" },
    { key: "1F9FD", label: "Esponja", group: "Artículos para el hogar" },
    { key: "1F56F", label: "Vela", group: "Artículos para el hogar" },
    { key: "1F4A1", label: "Ampolleta / foco", group: "Artículos para el hogar" },
    { key: "1F453", label: "Lentes", group: "Objetos casuales" },
    { key: "231A", label: "Reloj", group: "Objetos casuales" },
    { key: "1F392", label: "Mochila", group: "Objetos casuales" },
    { key: "1F45C", label: "Bolso", group: "Objetos casuales" },
    { key: "1F9E6", label: "Calcetines", group: "Objetos casuales" },
    { key: "1F511", label: "Llave", group: "Objetos casuales" },
    { key: "1F4F1", label: "Celular", group: "Objetos casuales" },
    { key: "1F381", label: "Regalo", group: "Objetos casuales" },
    { key: "1F455", label: "Playera / camisa", group: "Ropa" },
    { key: "1F9E2", label: "Gorra / cachucha", group: "Ropa" },
    { key: "1F45F", label: "Zapato", group: "Ropa" },
];
